name: tensorflow
dependencies:
  - apple::tensorflow-deps
  - black
  - boto3
  - flask
  - h5py
  - jupyter
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pandas-datareader
  - pillow
  - pip
  - pylint
  - python=3.8.12
  - pyyaml
  - requests
  - seaborn
  - scikit-learn
  - scipy
  - scikit-learn
  - statsmodels
  - tqdm
  - pip:
      - bayesian-optimization
      - gym
      - kaggle
      - tensorflow-macos
      - tensorflow-metal
